#!/bin/bash
# Claude Code Heartbeat — wrapper for systemd/launchd
# Runs /{{ SKILL_PREFIX }}-heartbeat from {{ WORK_DIR }}
# Generated by install.sh — do not edit manually

set -euo pipefail

LOG="$HOME/.claude/heartbeat-output.log"
LOCK="/tmp/claude-heartbeat-{{ AGENT_NAME }}.lock"

# Avoid overlap: if another heartbeat is running, skip
if [ -f "$LOCK" ]; then
  pid=$(cat "$LOCK" 2>/dev/null || echo "")
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    echo "--- skipped $(date -Iseconds) (pid $pid still running) ---" >> "$LOG"
    exit 0
  fi
  rm -f "$LOCK"
fi

echo $$ > "$LOCK"
trap "rm -f $LOCK" EXIT

echo "--- heartbeat $(date -Iseconds) ---" >> "$LOG"

cd {{ WORK_DIR }}

# Load secrets if available
SECRETS_DIR="{{ WORK_DIR }}/secrets"
if [ -d "$SECRETS_DIR" ]; then
  for f in "$SECRETS_DIR"/*.env; do
    [ -f "$f" ] && set -a && source "$f" && set +a
  done
fi

# Run preflight (zero tokens — bash only)
if [ -f "{{ WORK_DIR }}/tools/heartbeat-preflight.sh" ]; then
  PREFLIGHT=$(bash "{{ WORK_DIR }}/tools/heartbeat-preflight.sh" 2>/dev/null || echo "PREFLIGHT_WORK")
  echo "Preflight: $PREFLIGHT" >> "$LOG"
fi

# Run heartbeat via Claude Code
if claude -p "/{{ SKILL_PREFIX }}-heartbeat" \
  --max-turns 30 \
  --allowedTools "Bash(*),Read(*),Write(*),Edit(*),Glob(*),Grep(*),WebSearch(*),WebFetch(*),Task(*),Skill(*)" \
  >> "$LOG" 2>&1; then
  echo "--- done $(date -Iseconds) ---" >> "$LOG"
else
  echo "--- failed $(date -Iseconds) (exit code $?) ---" >> "$LOG"
fi

# Sync RAG index (if search system is installed)
if [ -f "{{ WORK_DIR }}/search/ingest.py" ]; then
  python3 "{{ WORK_DIR }}/search/ingest.py" \
    "{{ WORK_DIR }}/reports/" "{{ WORK_DIR }}/notes/" "{{ WORK_DIR }}/blog/entries/" \
    --no-embed --quiet 2>/dev/null || true
fi
