# kb.config — Knowledge Base do Negócio
# Generated by install.sh

agent: {{ AGENT_NAME }}

knowledge_base:
  type: {{ KB_TYPE }}       # local | git | url
  path: {{ KB_PATH }}       # local path, git URL, or https URL
  refresh: {{ KB_REFRESH }} # on-start | hourly | daily | manual

  # Instructions for agent when reading KB:
  loading_instruction: |
    Before starting any task, read the documents in {{ KB_PATH }}.
    They contain the business context, vocabulary, personas, processes and
    domain-specific constraints for {{ AGENT_DOMAIN }}.
    Prioritize these sources over any generic knowledge.

  # Priority files (filled by agent on first run):
  priority_files: []

  # Content index (auto-generated by agent):
  index: null
